version: '2'

services:
  web:
    build:
      context: ./
      args:
        dev_dependencies: "false"
    command: >
        sh -c " python3 manage.py migrate &&
                python3 manage.py compilemessages -l fr &&
                gunicorn geomapshark.wsgi -b :9000 --error-logfile gunicorn_log.log"
    volumes:
      - /var/sig/yverdon_geoportail/permis_fouille:/app_data
      - /var/sig/yverdon_geoportail/permis_fouille/tempfiles:/tempfiles
    ports:
      - "9095:9000"
  qgisserver:
      image: camptocamp/qgis-server:3.4
      container_name: qgis-server-geomapshark-print
      volumes:
          - .:/data
      ports:
          - "9096:80"
      environment:
          - QGIS_PROJECT_FILE=/data/print/print.qgs
          - PGSERVICEFILE=/data/print/pg_service.conf
