version: '2'

volumes:
  gmsdata:

services:
  web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code DEV ONLY!!!
      - gmsdata:/code/app_data
    ports:
      - "9095:9000"

  qgisserver:
      image: camptocamp/qgis-server:3.4
      container_name: qgis-server-geomapshark-print
      volumes:
          - .:/data
      ports:
          - "9096:80"
      environment:
          - QGIS_PROJECT_FILE=/data/print/print.qgs
          - PGSERVICEFILE=/data/print/pg_service.conf
