version: '2'

volumes:
  gmsdata:

services:
  web:
    image: gms_web
    depends_on:
      - "qgisserver"
      - "postgres"
    build: ./
    entrypoint: /code/entrypoint.sh
    command: python3 manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/code #DEV ONLY!!!
      - gmsdata:/code/app_data
    ports:
      - "9095:9000"

  qgisserver:
      image: camptocamp/qgis-server:3.10
      volumes:
          - .:/data
      ports:
          - "9096:80"
      environment:
          - QGIS_PROJECT_FILE=/data/qgisserver/geocity.qgs
          - PGSERVICEFILE=/data/qgisserver/pg_service.conf

  postgres:
      image: camptocamp/postgres:9.6
      environment:
        - POSTGRES_USER=geocity
        - POSTGRES_PASSWORD=geocity
      ports:
          - "9097:5432"
