version: '2'

services:
  web:
    build: .
    command: >
        sh -c " python3 manage.py runserver 0.0.0.0:9000 "
    volumes:
      - .:/code
      - C:/projets/geomapshark_files:/app_data
      - C:/projets/geomapshark_files/tempfiles:/tempfiles
      - C:/projets/geomapshark_files:/dumps_data
    ports:
      - "9095:9000"

  qgisserver:
      image: camptocamp/qgis-server:3.4
      container_name: qgis-server-geomapshark-print
      volumes:
          - .:/data
      ports:
          - "9096:80"
      environment:
          - QGIS_PROJECT_FILE=/data/print/print.qgs
          - PGSERVICEFILE=/data/print/pg_service.conf
